//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevCampExternalToolDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevCampExternalToolDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR CalenderStart =
        ///    DATE ( YEAR ( MIN ( @DateColumnName ) ), 1, 1 )
        ///VAR CalendarEnd =
        ///    DATE ( YEAR ( MAX ( @DateColumnName ) ), 12, 31 )
        ///RETURN
        ///    ADDCOLUMNS (
        ///        CALENDAR ( CalenderStart, CalendarEnd ),
        ///        &quot;Year&quot;, YEAR ( [Date] ),
        ///        &quot;Quarter&quot;, YEAR ( [Date] ) &amp; &quot; Q&quot; &amp; FORMAT( [Date], &quot;q&quot;),
        ///        &quot;Month&quot;, FORMAT ( [Date], &quot;MMMM&quot; ) &amp; &quot; &quot; &amp; YEAR ( [Date] ),
        ///        &quot;Day of Week&quot;, FORMAT ( [Date], &quot;dddd&quot; ),
        ///        &quot;MonthSort&quot;, (Year( [Date] ) * 100) + MONTH ( [Date] ),
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateCalendarTable_dax {
            get {
                return ResourceManager.GetString("CreateCalendarTable_dax", resourceCulture);
            }
        }
    }
}
